# Updated file: docker-compose.test.yml

services:
  web:
    build:
      context: .
      args:
        BUILD_VARIANT: ${BUILD_VARIANT:-gpu}
    container_name: class_genius_web
    user: "root"
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./segments:/app/segments
      - ./models:/app/models
      - ./workspace:/workspace
    environment:
      - REDIS_URL=redis://redis:6379/0
      # 👉 ADD THESE TWO DUMMY VARIABLES
      - RUNPOD_API_KEY=dummy_key_for_testing
      - RUNPOD_POD_ID=dummy_id_for_testing
    depends_on:
      - redis
    networks:
      - app-net

  redis:
    image: "redis:alpine"
    container_name: class_genius_redis
    restart: always
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
