version: '3.8'

services:
  web:
    build:
      context: .
      args:
        BUILD_VARIANT: ${BUILD_VARIANT:-gpu}
    container_name: class_genius_web
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./segments:/app/segments
      - ./models:/app/models
      - ./workspace:/workspace
    environment:
      # 👉 POINT TO THE REDIS SERVICE, NOT LOCALHOST
      - REDIS_URL=redis://redis:6379/0
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=all
    # 👉 ADD THIS TO MAKE WEB START AFTER REDIS
    depends_on:
      - redis
    # 👉 ADD THIS TO CONNECT TO THE SHARED NETWORK
    networks:
      - app-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # 👉 ADD THIS ENTIRE SERVICE BLOCK FOR REDIS
  redis:
    image: "redis:alpine"
    container_name: class_genius_redis
    restart: always
    # 👉 ADD THIS TO CONNECT TO THE SHARED NETWORK
    networks:
      - app-net

# 👉 ADD THIS NETWORK DEFINITION AT THE END
networks:
  app-net:
    driver: bridge
