version: '3.8'

services:
  web:
    build:
      context: .
      args:
        BUILD_VARIANT: ${BUILD_VARIANT:-gpu}
    container_name: class_genius_web
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./segments:/app/segments
      - ./models:/app/models
      - ./workspace:/workspace
    environment:
      - REDIS_URL=redis://localhost:6379/0  # Use local Redis
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
