name: Build and Test Docker Compose App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: docker-compose up --build -d

      - name: Wait for services to initialize
        run: sleep 15

      - name: Check container status
        run: docker-compose ps

      - name: Check Redis service logs
        run: docker-compose logs redis

      - name: Ping Redis from Web container
        run: docker-compose exec web ping -c 4 redis

      - name: Check web service logs
        run: docker-compose logs web
